#! /bin/bash

echo "Preparing:"
set -x                          # Output commands
set -e                          # Abort on errors

cd /scratch1/05765/dferg/simulations/D2.33_q1_a1_0_0_0_a2_0_0_0_m42.67_different_name/output-0000-active

module unload mvapich2
module load impi/18.0.5
module list

echo "Checking:"
pwd
hostname
date

echo "Environment:"
#export I_MPI_FABRICS=shm:ofa
#export I_MPI_MIC=1
#export I_MPI_OFA_ADAPTER_NAME=mlx4_0
export CACTUS_NUM_PROCS=56
export CACTUS_NUM_THREADS=1
export CACTUS_SET_THREAD_BINDINGS=1
export CXX_MAX_TASKS=500
export GMON_OUT_PREFIX=gmon.out
export OMP_MAX_TASKS=500
export OMP_NUM_THREADS=1
export OMP_STACKSIZE=8192       # kByte
export PTHREAD_MAX_TASKS=500
# see http://pages.tacc.utexas.edu/~eijkhout/pcse/html/omp-affinity.html
# stampede2 enables hyperthreading so in principle there are 96 logical cores
export OMP_PLACES=cores
export OMP_PROC_BIND=close
env | sort > SIMFACTORY/ENVIRONMENT
echo ${SLURM_NODELIST} > NODES

echo "Starting:"
export CACTUS_STARTTIME=$(date +%s)
time ibrun -n 56 /scratch1/05765/dferg/simulations/D2.33_q1_a1_0_0_0_a2_0_0_0_m42.67_different_name/SIMFACTORY/exe/cactus_bbh-maya -L 3 /scratch1/05765/dferg/simulations/D2.33_q1_a1_0_0_0_a2_0_0_0_m42.67_different_name/output-0000/D2.33_q1_a1_0_0_0_a2_0_0_0_m42.67.par

echo "Stopping:"
date

echo "Done."
