#! /bin/bash
#SBATCH -A PHY20039
#SBATCH -p development
#SBATCH -t 2:00:00
#SBATCH -N 1 -n 56
#SBATCH 
#SBATCH -J D2.33_q1_a1_0_0
#SBATCH --mail-type=ALL
#SBATCH --mail-user=deborah.ferguson@austin.utexas.edu
#SBATCH -o /scratch1/05765/dferg/simulations/D2.33_q1_a1_0_0_0_a2_0_0_0_m42.67_different_name/output-0000/D2.33_q1_a1_0_0_0_a2_0_0_0_m42.67_different_name.out
#SBATCH -e /scratch1/05765/dferg/simulations/D2.33_q1_a1_0_0_0_a2_0_0_0_m42.67_different_name/output-0000/D2.33_q1_a1_0_0_0_a2_0_0_0_m42.67_different_name.err
cd /work/05765/dferg/frontera/Cactus
/work/05765/dferg/frontera/Cactus/repos/simfactory2/bin/sim run D2.33_q1_a1_0_0_0_a2_0_0_0_m42.67_different_name --basedir=/scratch1/05765/dferg/simulations --machine=frontera-clx --restart-id=0 
