#! /bin/bash

echo "Preparing:"
set -x                          # Output commands
set -e                          # Abort on errors

cd @RUNDIR@-active

module unload mvapich2
module load impi/18.0.2
module list

echo "Checking:"
pwd
hostname
date

echo "Environment:"
#export I_MPI_FABRICS=shm:ofa
#export I_MPI_MIC=1
#export I_MPI_OFA_ADAPTER_NAME=mlx4_0
export CACTUS_NUM_PROCS=@NUM_PROCS@
export CACTUS_NUM_THREADS=@NUM_THREADS@
export CACTUS_SET_THREAD_BINDINGS=1
export CXX_MAX_TASKS=500
export GMON_OUT_PREFIX=gmon.out
export OMP_MAX_TASKS=500
export OMP_NUM_THREADS=@NUM_THREADS@
export OMP_STACKSIZE=8192       # kByte
export PTHREAD_MAX_TASKS=500
# see http://pages.tacc.utexas.edu/~eijkhout/pcse/html/omp-affinity.html
# stampede2 enables hyperthreading so in principle there are 96 logical cores
export OMP_PLACES=cores
export OMP_PROC_BIND=close
env | sort > SIMFACTORY/ENVIRONMENT
echo ${SLURM_NODELIST} > NODES

echo "Starting:"
export CACTUS_STARTTIME=$(date +%s)
time ibrun @EXECUTABLE@ -L 3 @PARFILE@

echo "Stopping:"
date

echo "Done."

should_continue=`@SOURCEDIR@/utils/should_continue_run.py @RUNDIR@`

SIMFACTORY=@SIMFACTORY@
# old version of simfactory (ET_2020_05 and older) do not provide                                                                                                                                     
# SIMFACTORY in RunScript, so try to work around                                                                                                                                                      
if echo "$SIMFACTORY" | grep -qF '@' ; then
    SIMFACTORY=@SOURCEDIR@/simfactory/bin/sim
fi

if [ "$should_continue" == "true" ] ; then
    cd @SOURCEDIR@
    ssh login1 $SIMFACTORY submit --basedir=/scratch/06913/ryan_n16/simulations --machine=stampede2-skx @SIMULATION_NAME@
fi
